[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
   from = "https://servezy.in/*"
   to = "https://servezy.in/:splat"
   status = 301
   force = true
   